apiVersion: v1
kind: Service
metadata:
  name: client-gateway
spec:
  type: LoadBalancer
  selector:
    app: client-gateway
  ports:
    - name: http
      protocol: TCP
      port: 31055
      targetPort: 3000